#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

password="$YNH_APP_ARG_PASSWORD"
random=$(ynh_string_random --length=24)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression "Storing installation settings..."

ynh_app_setting_set --key=random --value=$random
ynh_app_setting_set --key=password --value="$password"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

# Install French language
ynh_setup_source --dest_dir="$install_dir/user/languages" --source_id="fr"

ynh_config_add --template="index.php" --destination="$install_dir/index.php"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config-sample.php" --destination="$install_dir/user/config.php"

chmod 600 "$install_dir/user/config.php"
chown $app:$app "$install_dir/user/config.php"

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression "Finalizing installation..."

ynh_local_curl "admin/install.php" "install=dummy"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
